
/**************************************************************
 *	
 *	calmstreams, 8 bit, 11025Hz,
 *	1 channel, 1335128 bytes/channel
 *	Total Size: 1 * 1335128 + 4 (header) = 1335172 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/jennakohls/CS2261/M04/calmstreams.wav
 *	Time-stamp: Sun Dec 02 22:40:12 2018
 *	
 **************************************************************/

#ifndef __CALMSTREAMSH__
#define __CALMSTREAMSH__

#define CALMSTREAMSFREQ 11025
#define CALMSTREAMSLEN 1335128

extern const unsigned char calmstreams[1335128];

#endif /* __CALMSTREAMSH__ */
