
/**************************************************************
 *	
 *	enemyhit, 8 bit, 11025Hz,
 *	1 channel, 2088 bytes/channel
 *	Total Size: 1 * 2088 + 4 (header) = 2132 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/jennakohls/CS2261/M04/enemyhit.wav
 *	Time-stamp: Sun Dec 02 23:11:54 2018
 *	
 **************************************************************/

#ifndef __ENEMYHITH__
#define __ENEMYHITH__

#define ENEMYHITFREQ 11025
#define ENEMYHITLEN 2088

extern const unsigned char enemyhit[2088];

#endif /* __ENEMYHITH__ */
