
/**************************************************************
 *	
 *	playerhit, 8 bit, 11025Hz,
 *	1 channel, 2586 bytes/channel
 *	Total Size: 1 * 2586 + 4 (header) = 2630 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/jennakohls/CS2261/M04/playerhit.wav
 *	Time-stamp: Sun Dec 02 23:06:13 2018
 *	
 **************************************************************/

#ifndef __PLAYERHITH__
#define __PLAYERHITH__

#define PLAYERHITFREQ 11025
#define PLAYERHITLEN 2586

extern const unsigned char playerhit[2586];

#endif /* __PLAYERHITH__ */
